### PR TITLE
Feat:lesson3

### PR DESCRIPTION
**Pull request by sae-github**
# [Lesson3](https://github.com/sae-github/handsonFrontend/blob/master/work/markup/1.md#3)
### Specification Description
- I used DocumentFragment to put the nodes together and insert them together.

[comment]
I was confused by the many ways to add nodes.
In particular, I was wondering if I should use the` append` method or the `appendChild` method.
The append method is not supported by IE, so I used appendChild this time.

Please leave a review.

### CODE REVIEW

**Comment by kenmori** [comment]
> The append method is not supported by IE, so I used appendChild this time.

good.

**Comment by kenmori** [comment]
I show you append vs appendChild

**append**
append can pass mulitipul Node.

```js
li.append(anchor, image);
```


result
```html
<li><a href="a1.html">a1</a><img src="/img/bookmark.png"></li>
```

**appendChild**
```js
li.appendChild(anchor).appendChild(image);
```

result

```html
<li><a href="a1.html"><img src="/img/bookmark.png">a1</a></li>
```

and

`append` can pass text as arguments

```js
append("text")
```

this is valid.

but

`appendChild` can’ t it

```js
appendChild("text") // ×
TypeError
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
```

**Comment by kenmori** [comment]
Approve

**Comment by sae-github** [comment]
> I show you append vs appendChild

Thank you for taking the time to do this.
It was very informative.
I would like to understand the characteristics of the two and choose a better method if necessary.

**Comment by sae-github** [comment]
> Approve

Thank you for your review.
I'll merge.🥳

**Pull request merged**
